### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by freakboy3742**
A variety of small housekeeping tasks:

* Replaces Travis CI with Github Actions; Travis has become hostile to FLOSS communities, and has had some disturbing security breaches to boot.
* Cleans up the docs configuration (including fixing some markup errors that were preventing docs from building)
* Modernises the project layout, introducing a `src` folder, a `setup.cfg` file, and a MANIFEST.in file,
* Adds a tox configuration to make running tests easier (`python setup.py test` has been deprecated)
* Applies flake8 to the codebase
* Deprecates unsupported versions of Python, and the code needed to support them.

### CODE REVIEW

**Comment by freakboy3742** [comment]
@al45tair Could I ask you to either (a) enable Github Actions in the project settings, or (b) grant me permissions to edit project settings (the latter would be preferable)?

**Comment by freakboy3742** [comment]
@al45tair Also - Could I get permissions on ReadTheDocs, in case of any problems there? Thanks!

**Comment by al45tair** [comment]
Permissions are an interesting problem; apparently repos in personal accounts essentially can't set permissions. I'd need to transfer the projects to an organisation to do that, which might be a good idea anyway.

**Comment by freakboy3742** [comment]
I'm happy to host as part of the BeeWare org if that helps.

**Comment by al45tair** [comment]
I've added you as a maintainer on ReadTheDocs.

**Comment by al45tair** [comment]
I've created a "dmgbuild" organisation and transferred all three projects to that. I've also made you an owner of that organisation. Seems like a good idea to have the project have its own organisation, since people are actively using it.

My guess is that that will require some tweaks on ReadTheDocs. It's probably totally broken Travis, but if you're switching to Github Actions we don't care about that.

**Comment by freakboy3742** [comment]
Awesome - thanks.

And yes - I was expected some RTD changes would be required. GitHub Actions will probably take a couple of attempts to get fully working.

**Pull request merged**
